#!/usr/bin/env bash
# Script that displays information about subdomains

# domain information function displays subdomain, its record type and the ip addr it points to
domain_information (){
	record_plus_ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $record_plus_ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to "$3}'
}

# $# is a special variable that represents no. of args passed to a script

if [ "$#" == 1 ];
then
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_information "$1" "web-02"
elif [ "$#" == 2 ];
then
	domain_information "$1" "$2"
fi
