#!/usr/bin/env bash
# Install NGINX web server

sudo apt -y update
sudo apt -y install nginx

if [ $? -eq 0]
then
    # set up nginx to listen on port 80
    echo -e \
"http {
	server	{
		listen	80;
		location / {
			root	/var/www/school;
			index	/index.html;
		}
	}
}
events	{
}" | sudo tee /etc/nginx/nginx.conf
    sudo mkdir -p /var/www/school
    echo "Hello World!" | sudo tee /var/www/school/index.html

    # restart nginx
    sudo service nginx start

else
    echo "Nginx installation error"
    exit 1
fi
exit 0
