#!/usr/bin/env bash
# adding custom nginx response header

sudo apt update && sudo apt install nginx

sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo -e \
"server	{
	listen 80 default_server;
	listen [::]:80 default_server;

	location / {
		root	/var/www/html;
		index	/index.html;
		add_header X-Served-By $HOSTNAME;
	}

	location /redirect_me {
		return 301 http://youtube.com/;
	}

	error_page 404 /404.html;

	location /404 {
		root /var/www/html;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
