#!/usr/bin/env bash
# FizzBuzz

n=100

for (( i=1 ; i<=n ; i++));
do
	if [ $((i % 3)) == 0 ] && [ $((i % 5)) != 0 ];
	then
		echo "Fizz"
	elif [ $((i % 3)) != 0 ] && [ $((i % 5)) == 0 ];
	then
		echo "Buzz"
	elif [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ];
	then
		echo "FizzBuzz"
	else
		echo $i
	fi
done
