#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# displays 4 and then "bad luck from China" for 4th iteration
# displays 9 and then "bad luck from Japan" for 9th iteration
# displays 17 and then "bad luck from Italy" for 17th iterations

i=1

while [ $i -le 20 ];
do
	case $i in

		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac

	((i++))
done
