#!/usr/bin/env bash
# Bash script that listens on port 98 on localhost
# nc(or netcat) utility can be used to listen on arbitrary TCP and UDP ports
# -l flag: Used to specify that nc should listen for an incoming connection
#          rather than initiate a connection to a remote host.

nc -l localhost 98
